"""Add jd_parsed_at column to scoring_jobs

Revision ID: d323aee86632
Revises: 003_add_candidate_review_status
Create Date: 2026-04-08 19:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd323aee86632'
down_revision: Union[str, None] = '003_add_candidate_review_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_jobs', sa.Column('jd_parsed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scoring_jobs', 'jd_parsed_at')
    # ### end Alembic commands ###
